// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package pgsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM users WHERE is_admin = TRUE
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, token, device_id, device_os, device_version, device_name, expires_at, created_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3::uuid, $4, $5, $6, $7, NOW())
RETURNING id::text, user_id::text, token, device_id::text, device_os, device_version, device_name, expires_at, created_at
`

type CreateSessionParams struct {
	Column1       uuid.UUID      `json:"column_1"`
	Token         string         `json:"token"`
	Column3       uuid.UUID      `json:"column_3"`
	DeviceOs      sql.NullString `json:"device_os"`
	DeviceVersion sql.NullString `json:"device_version"`
	DeviceName    sql.NullString `json:"device_name"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

type CreateSessionRow struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Token         string         `json:"token"`
	DeviceID      string         `json:"device_id"`
	DeviceOs      sql.NullString `json:"device_os"`
	DeviceVersion sql.NullString `json:"device_version"`
	DeviceName    sql.NullString `json:"device_name"`
	ExpiresAt     time.Time      `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Column1,
		arg.Token,
		arg.Column3,
		arg.DeviceOs,
		arg.DeviceVersion,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.DeviceID,
		&i.DeviceOs,
		&i.DeviceVersion,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, is_premium, is_admin, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, FALSE, FALSE, NOW(), NOW())
RETURNING id::text, username, password_hash, is_premium, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	IsPremium    bool      `json:"is_premium"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsPremium,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAdmin = `-- name: CreateUserAdmin :one
INSERT INTO users (id, username, password_hash, is_premium, is_admin, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, FALSE, TRUE, NOW(), NOW())
RETURNING id::text, username, password_hash, is_premium, is_admin, created_at, updated_at
`

type CreateUserAdminParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserAdminRow struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	IsPremium    bool      `json:"is_premium"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) (CreateUserAdminRow, error) {
	row := q.db.QueryRowContext(ctx, createUserAdmin, arg.Username, arg.PasswordHash)
	var i CreateUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsPremium,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteSessionByIDParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, arg.Column1, arg.Column2)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const deleteSessionsByDeviceID = `-- name: DeleteSessionsByDeviceID :exec
DELETE FROM sessions WHERE device_id = $1::uuid
`

func (q *Queries) DeleteSessionsByDeviceID(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByDeviceID, dollar_1)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id::text, user_id::text, token, device_id::text, device_os, device_version, device_name, expires_at, created_at
FROM sessions
WHERE token = $1
`

type GetSessionByTokenRow struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Token         string         `json:"token"`
	DeviceID      string         `json:"device_id"`
	DeviceOs      sql.NullString `json:"device_os"`
	DeviceVersion sql.NullString `json:"device_version"`
	DeviceName    sql.NullString `json:"device_name"`
	ExpiresAt     time.Time      `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.DeviceID,
		&i.DeviceOs,
		&i.DeviceVersion,
		&i.DeviceName,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id::text, username, password_hash, is_premium, is_admin, created_at, updated_at
FROM users
WHERE id = $1::uuid
`

type GetUserByIDRow struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	IsPremium    bool      `json:"is_premium"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, dollar_1)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsPremium,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id::text, username, password_hash, is_premium, is_admin, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	IsPremium    bool      `json:"is_premium"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsPremium,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id::text, user_id::text, token, device_id::text, device_os, device_version, device_name, expires_at, created_at
FROM sessions
WHERE user_id = $1::uuid AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListSessionsByUserRow struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Token         string         `json:"token"`
	DeviceID      string         `json:"device_id"`
	DeviceOs      sql.NullString `json:"device_os"`
	DeviceVersion sql.NullString `json:"device_version"`
	DeviceName    sql.NullString `json:"device_name"`
	ExpiresAt     time.Time      `json:"expires_at"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, dollar_1 uuid.UUID) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.DeviceID,
			&i.DeviceOs,
			&i.DeviceVersion,
			&i.DeviceName,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id::text, username, is_premium, is_admin, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	IsPremium bool      `json:"is_premium"`
	IsAdmin   bool      `json:"is_admin"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsPremium,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPremium = `-- name: SetUserPremium :exec
UPDATE users
SET is_premium = $1, updated_at = NOW()
WHERE id = $2::uuid
`

type SetUserPremiumParams struct {
	IsPremium bool      `json:"is_premium"`
	Column2   uuid.UUID `json:"column_2"`
}

func (q *Queries) SetUserPremium(ctx context.Context, arg SetUserPremiumParams) error {
	_, err := q.db.ExecContext(ctx, setUserPremium, arg.IsPremium, arg.Column2)
	return err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :exec
UPDATE users
SET is_admin = $1, updated_at = NOW()
WHERE id = $2::uuid
`

type UpdateUserAdminParams struct {
	IsAdmin bool      `json:"is_admin"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAdmin, arg.IsAdmin, arg.Column2)
	return err
}

const updateUserPremium = `-- name: UpdateUserPremium :exec
UPDATE users
SET is_premium = $1, updated_at = NOW()
WHERE id = $2::uuid
`

type UpdateUserPremiumParams struct {
	IsPremium bool      `json:"is_premium"`
	Column2   uuid.UUID `json:"column_2"`
}

func (q *Queries) UpdateUserPremium(ctx context.Context, arg UpdateUserPremiumParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPremium, arg.IsPremium, arg.Column2)
	return err
}
