// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package pgsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelSubscriptionByUser = `-- name: CancelSubscriptionByUser :exec
UPDATE subscriptions SET status = 'canceled', updated_at = CURRENT_TIMESTAMP WHERE user_id::text = $1
`

func (q *Queries) CancelSubscriptionByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelSubscriptionByUser, userID)
	return err
}

const getSubscriptionByUser = `-- name: GetSubscriptionByUser :one
SELECT id::text, user_id::text, stripe_customer_id, stripe_subscription_id,
       status, plan_id, current_period_end, created_at, updated_at
FROM subscriptions
WHERE user_id::text = $1
`

type GetSubscriptionByUserRow struct {
	ID                   string       `json:"id"`
	UserID               string       `json:"user_id"`
	StripeCustomerID     string       `json:"stripe_customer_id"`
	StripeSubscriptionID string       `json:"stripe_subscription_id"`
	Status               string       `json:"status"`
	PlanID               string       `json:"plan_id"`
	CurrentPeriodEnd     sql.NullTime `json:"current_period_end"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

func (q *Queries) GetSubscriptionByUser(ctx context.Context, userID uuid.UUID) (GetSubscriptionByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUser, userID)
	var i GetSubscriptionByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.PlanID,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPremiumFlag = `-- name: GetUserPremiumFlag :one
SELECT is_premium FROM users WHERE id::text = $1
`

func (q *Queries) GetUserPremiumFlag(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, getUserPremiumFlag, id)
	var is_premium bool
	err := row.Scan(&is_premium)
	return is_premium, err
}

const setUserPremiumFalse = `-- name: SetUserPremiumFalse :exec
UPDATE users SET is_premium = FALSE, updated_at = CURRENT_TIMESTAMP WHERE id::text = $1
`

func (q *Queries) SetUserPremiumFalse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setUserPremiumFalse, id)
	return err
}

const setUserPremiumTrue = `-- name: SetUserPremiumTrue :exec
UPDATE users SET is_premium = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id::text = $1
`

func (q *Queries) SetUserPremiumTrue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setUserPremiumTrue, id)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (id, user_id, stripe_customer_id, stripe_subscription_id, status, plan_id, current_period_end, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE SET
  stripe_customer_id = EXCLUDED.stripe_customer_id,
  stripe_subscription_id = EXCLUDED.stripe_subscription_id,
  status = EXCLUDED.status,
  plan_id = EXCLUDED.plan_id,
  current_period_end = EXCLUDED.current_period_end,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSubscriptionParams struct {
	Column1              uuid.UUID    `json:"column_1"`
	StripeCustomerID     string       `json:"stripe_customer_id"`
	StripeSubscriptionID string       `json:"stripe_subscription_id"`
	Status               string       `json:"status"`
	PlanID               string       `json:"plan_id"`
	CurrentPeriodEnd     sql.NullTime `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.Column1,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.PlanID,
		arg.CurrentPeriodEnd,
	)
	return err
}
