// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package pgsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, 'pending', $3, '', '', '', NOW(), NOW())
RETURNING id::text, user_id::text, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	Column1  uuid.UUID `json:"column_1"`
	Type     string    `json:"type"`
	InputRef string    `json:"input_ref"`
}

type CreateJobRow struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Type       string       `json:"type"`
	Status     string       `json:"status"`
	InputRef   string       `json:"input_ref"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	WorkerID   string       `json:"worker_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (CreateJobRow, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Column1, arg.Type, arg.InputRef)
	var i CreateJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.InputRef,
		&i.OutputRef,
		&i.Error,
		&i.WorkerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByIDForUser = `-- name: GetJobByIDForUser :one
SELECT id::text, user_id::text, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE id::text = $1 AND user_id::text = $2
`

type GetJobByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetJobByIDForUserRow struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Type       string       `json:"type"`
	Status     string       `json:"status"`
	InputRef   string       `json:"input_ref"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	WorkerID   string       `json:"worker_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) GetJobByIDForUser(ctx context.Context, arg GetJobByIDForUserParams) (GetJobByIDForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getJobByIDForUser, arg.ID, arg.UserID)
	var i GetJobByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.InputRef,
		&i.OutputRef,
		&i.Error,
		&i.WorkerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id::text, user_id::text, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE user_id::text = $1
ORDER BY created_at DESC
LIMIT 50
`

type ListJobsByUserRow struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Type       string       `json:"type"`
	Status     string       `json:"status"`
	InputRef   string       `json:"input_ref"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	WorkerID   string       `json:"worker_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) ListJobsByUser(ctx context.Context, userID uuid.UUID) ([]ListJobsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByUserRow
	for rows.Next() {
		var i ListJobsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.InputRef,
			&i.OutputRef,
			&i.Error,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUserAndType = `-- name: ListJobsByUserAndType :many
SELECT id::text, user_id::text, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE user_id::text = $1 AND type = $2
ORDER BY created_at DESC
LIMIT 50
`

type ListJobsByUserAndTypeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

type ListJobsByUserAndTypeRow struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	Type       string       `json:"type"`
	Status     string       `json:"status"`
	InputRef   string       `json:"input_ref"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	WorkerID   string       `json:"worker_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

func (q *Queries) ListJobsByUserAndType(ctx context.Context, arg ListJobsByUserAndTypeParams) ([]ListJobsByUserAndTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUserAndType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsByUserAndTypeRow
	for rows.Next() {
		var i ListJobsByUserAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.InputRef,
			&i.OutputRef,
			&i.Error,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $1, output_ref = $2, error = $3,
    started_at = COALESCE($4, started_at),
    finished_at = COALESCE($5, finished_at),
    updated_at = CURRENT_TIMESTAMP
WHERE id::text = $6
`

type UpdateJobStatusParams struct {
	Status     string       `json:"status"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	ID         uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.OutputRef,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
