// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgsqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	DeviceName     string    `json:"device_name"`
	PublicKey      string    `json:"public_key"`
	WrappedUserKey string    `json:"wrapped_user_key"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type EncryptedNote struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

type EncryptedRecording struct {
	ID            uuid.UUID    `json:"id"`
	UserID        uuid.UUID    `json:"user_id"`
	ObjectKey     string       `json:"object_key"`
	SizeBytes     int64        `json:"size_bytes"`
	ContentNonce  []byte       `json:"content_nonce"`
	EncryptedMeta []byte       `json:"encrypted_meta"`
	Version       int32        `json:"version"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type Job struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Type       string       `json:"type"`
	Status     string       `json:"status"`
	InputRef   string       `json:"input_ref"`
	OutputRef  string       `json:"output_ref"`
	Error      string       `json:"error"`
	WorkerID   string       `json:"worker_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	StartedAt  sql.NullTime `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Subscription struct {
	ID                   uuid.UUID    `json:"id"`
	UserID               uuid.UUID    `json:"user_id"`
	StripeCustomerID     string       `json:"stripe_customer_id"`
	StripeSubscriptionID string       `json:"stripe_subscription_id"`
	Status               string       `json:"status"`
	PlanID               string       `json:"plan_id"`
	CurrentPeriodEnd     sql.NullTime `json:"current_period_end"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

type SyncCursor struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	DeviceID  uuid.UUID `json:"device_id"`
	Entity    string    `json:"entity"`
	Cursor    time.Time `json:"cursor"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	IsPremium    bool      `json:"is_premium"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
