// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package pgsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, '', NOW(), NOW())
RETURNING id::text, user_id::text, device_name, public_key, wrapped_user_key, last_seen_at, created_at
`

type CreateDeviceParams struct {
	Column1    uuid.UUID `json:"column_1"`
	DeviceName string    `json:"device_name"`
	PublicKey  string    `json:"public_key"`
}

type CreateDeviceRow struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	DeviceName     string    `json:"device_name"`
	PublicKey      string    `json:"public_key"`
	WrappedUserKey string    `json:"wrapped_user_key"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.Column1, arg.DeviceName, arg.PublicKey)
	var i CreateDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.PublicKey,
		&i.WrappedUserKey,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSyncNote = `-- name: CreateSyncNote :one
INSERT INTO sync_notes (id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, 1, $4, NOW(), NOW())
RETURNING id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type CreateSyncNoteParams struct {
	Column1      uuid.UUID `json:"column_1"`
	ObjectKey    string    `json:"object_key"`
	PayloadSize  int64     `json:"payload_size"`
	RecordingRef string    `json:"recording_ref"`
}

type CreateSyncNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreateSyncNote(ctx context.Context, arg CreateSyncNoteParams) (CreateSyncNoteRow, error) {
	row := q.db.QueryRowContext(ctx, createSyncNote,
		arg.Column1,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
	)
	var i CreateSyncNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSyncRecording = `-- name: CreateSyncRecording :one
INSERT INTO sync_recordings (id, user_id, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, $4, $5, 1, NOW(), NOW())
RETURNING id::text, user_id::text, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at, deleted_at
`

type CreateSyncRecordingParams struct {
	Column1      uuid.UUID `json:"column_1"`
	ObjectKey    string    `json:"object_key"`
	SizeBytes    int64     `json:"size_bytes"`
	ContentNonce []byte    `json:"content_nonce"`
	Meta         []byte    `json:"meta"`
}

type CreateSyncRecordingRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	SizeBytes    int64        `json:"size_bytes"`
	ContentNonce []byte       `json:"content_nonce"`
	Meta         []byte       `json:"meta"`
	Version      int32        `json:"version"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreateSyncRecording(ctx context.Context, arg CreateSyncRecordingParams) (CreateSyncRecordingRow, error) {
	row := q.db.QueryRowContext(ctx, createSyncRecording,
		arg.Column1,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentNonce,
		arg.Meta,
	)
	var i CreateSyncRecordingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentNonce,
		&i.Meta,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id::text = $1 AND user_id::text = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor
FROM sync_cursors
WHERE device_id::text = $1 AND entity = $2
`

type GetSyncCursorParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Entity   string    `json:"entity"`
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.DeviceID, arg.Entity)
	var cursor time.Time
	err := row.Scan(&cursor)
	return cursor, err
}

const getSyncNote = `-- name: GetSyncNote :one
SELECT id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM sync_notes
WHERE id::text = $1 AND user_id::text = $2
`

type GetSyncNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetSyncNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetSyncNote(ctx context.Context, arg GetSyncNoteParams) (GetSyncNoteRow, error) {
	row := q.db.QueryRowContext(ctx, getSyncNote, arg.ID, arg.UserID)
	var i GetSyncNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id::text, user_id::text, device_name, public_key, wrapped_user_key, last_seen_at, created_at
FROM devices
WHERE user_id::text = $1
ORDER BY created_at
`

type ListDevicesByUserRow struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	DeviceName     string    `json:"device_name"`
	PublicKey      string    `json:"public_key"`
	WrappedUserKey string    `json:"wrapped_user_key"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]ListDevicesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesByUserRow
	for rows.Next() {
		var i ListDevicesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.PublicKey,
			&i.WrappedUserKey,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncNoteChanges = `-- name: ListSyncNoteChanges :many
SELECT id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM sync_notes
WHERE user_id::text = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListSyncNoteChangesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type ListSyncNoteChangesRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListSyncNoteChanges(ctx context.Context, arg ListSyncNoteChangesParams) ([]ListSyncNoteChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncNoteChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncNoteChangesRow
	for rows.Next() {
		var i ListSyncNoteChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.PayloadSize,
			&i.Version,
			&i.RecordingRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRecordingChanges = `-- name: ListSyncRecordingChanges :many
SELECT id::text, user_id::text, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at, deleted_at
FROM sync_recordings
WHERE user_id::text = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListSyncRecordingChangesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type ListSyncRecordingChangesRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	SizeBytes    int64        `json:"size_bytes"`
	ContentNonce []byte       `json:"content_nonce"`
	Meta         []byte       `json:"meta"`
	Version      int32        `json:"version"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListSyncRecordingChanges(ctx context.Context, arg ListSyncRecordingChangesParams) ([]ListSyncRecordingChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRecordingChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncRecordingChangesRow
	for rows.Next() {
		var i ListSyncRecordingChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentNonce,
			&i.Meta,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingOwnedByUser = `-- name: RecordingOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM sync_recordings
  WHERE object_key = $1 AND user_id::text = $2
)
`

type RecordingOwnedByUserParams struct {
	ObjectKey string    `json:"object_key"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordingOwnedByUser(ctx context.Context, arg RecordingOwnedByUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, recordingOwnedByUser, arg.ObjectKey, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteSyncNote = `-- name: SoftDeleteSyncNote :execrows
UPDATE sync_notes
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id::text = $1 AND user_id::text = $2 AND deleted_at IS NULL
`

type SoftDeleteSyncNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteSyncNote(ctx context.Context, arg SoftDeleteSyncNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteSyncNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteSyncRecording = `-- name: SoftDeleteSyncRecording :execrows
UPDATE sync_recordings
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id::text = $1 AND user_id::text = $2 AND deleted_at IS NULL
`

type SoftDeleteSyncRecordingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteSyncRecording(ctx context.Context, arg SoftDeleteSyncRecordingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteSyncRecording, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceKey = `-- name: UpdateDeviceKey :execrows
UPDATE devices
SET wrapped_user_key = $1, last_seen_at = CURRENT_TIMESTAMP
WHERE id::text = $2 AND user_id::text = $3
`

type UpdateDeviceKeyParams struct {
	WrappedUserKey string    `json:"wrapped_user_key"`
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateDeviceKey(ctx context.Context, arg UpdateDeviceKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeviceKey, arg.WrappedUserKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSyncNote = `-- name: UpdateSyncNote :one
UPDATE sync_notes
SET object_key = $1, payload_size = $2, recording_ref = $3,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id::text = $4 AND user_id::text = $5 AND version = $6
RETURNING id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type UpdateSyncNoteParams struct {
	ObjectKey    string    `json:"object_key"`
	PayloadSize  int64     `json:"payload_size"`
	RecordingRef string    `json:"recording_ref"`
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Version      int32     `json:"version"`
}

type UpdateSyncNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpdateSyncNote(ctx context.Context, arg UpdateSyncNoteParams) (UpdateSyncNoteRow, error) {
	row := q.db.QueryRowContext(ctx, updateSyncNote,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i UpdateSyncNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (id, user_id, device_id, entity, cursor, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2::uuid, $3, $4, NOW())
ON CONFLICT (device_id, entity)
DO UPDATE SET cursor = $4, updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Entity  string    `json:"entity"`
	Cursor  time.Time `json:"cursor"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor,
		arg.Column1,
		arg.Column2,
		arg.Entity,
		arg.Cursor,
	)
	return err
}
