// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package pgsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, '', NOW(), NOW())
RETURNING id::text, user_id::text, device_name, public_key, wrapped_user_key, last_seen_at, created_at
`

type CreateDeviceParams struct {
	Column1    uuid.UUID `json:"column_1"`
	DeviceName string    `json:"device_name"`
	PublicKey  string    `json:"public_key"`
}

type CreateDeviceRow struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	DeviceName     string    `json:"device_name"`
	PublicKey      string    `json:"public_key"`
	WrappedUserKey string    `json:"wrapped_user_key"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.Column1, arg.DeviceName, arg.PublicKey)
	var i CreateDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.PublicKey,
		&i.WrappedUserKey,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEncryptedNote = `-- name: CreateEncryptedNote :one
INSERT INTO encrypted_notes (id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, 1, $4, NOW(), NOW())
RETURNING id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type CreateEncryptedNoteParams struct {
	Column1      uuid.UUID `json:"column_1"`
	ObjectKey    string    `json:"object_key"`
	PayloadSize  int64     `json:"payload_size"`
	RecordingRef string    `json:"recording_ref"`
}

type CreateEncryptedNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreateEncryptedNote(ctx context.Context, arg CreateEncryptedNoteParams) (CreateEncryptedNoteRow, error) {
	row := q.db.QueryRowContext(ctx, createEncryptedNote,
		arg.Column1,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
	)
	var i CreateEncryptedNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEncryptedRecording = `-- name: CreateEncryptedRecording :one
INSERT INTO encrypted_recordings (id, user_id, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2, $3, $4, $5, 1, NOW(), NOW())
RETURNING id::text, user_id::text, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at, deleted_at
`

type CreateEncryptedRecordingParams struct {
	Column1       uuid.UUID `json:"column_1"`
	ObjectKey     string    `json:"object_key"`
	SizeBytes     int64     `json:"size_bytes"`
	ContentNonce  []byte    `json:"content_nonce"`
	EncryptedMeta []byte    `json:"encrypted_meta"`
}

type CreateEncryptedRecordingRow struct {
	ID            string       `json:"id"`
	UserID        string       `json:"user_id"`
	ObjectKey     string       `json:"object_key"`
	SizeBytes     int64        `json:"size_bytes"`
	ContentNonce  []byte       `json:"content_nonce"`
	EncryptedMeta []byte       `json:"encrypted_meta"`
	Version       int32        `json:"version"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreateEncryptedRecording(ctx context.Context, arg CreateEncryptedRecordingParams) (CreateEncryptedRecordingRow, error) {
	row := q.db.QueryRowContext(ctx, createEncryptedRecording,
		arg.Column1,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentNonce,
		arg.EncryptedMeta,
	)
	var i CreateEncryptedRecordingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentNonce,
		&i.EncryptedMeta,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id::text = $1 AND user_id::text = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getEncryptedNote = `-- name: GetEncryptedNote :one
SELECT id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM encrypted_notes
WHERE id::text = $1 AND user_id::text = $2
`

type GetEncryptedNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetEncryptedNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetEncryptedNote(ctx context.Context, arg GetEncryptedNoteParams) (GetEncryptedNoteRow, error) {
	row := q.db.QueryRowContext(ctx, getEncryptedNote, arg.ID, arg.UserID)
	var i GetEncryptedNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor
FROM sync_cursors
WHERE device_id::text = $1 AND entity = $2
`

type GetSyncCursorParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	Entity   string    `json:"entity"`
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.DeviceID, arg.Entity)
	var cursor time.Time
	err := row.Scan(&cursor)
	return cursor, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id::text, user_id::text, device_name, public_key, wrapped_user_key, last_seen_at, created_at
FROM devices
WHERE user_id::text = $1
ORDER BY created_at
`

type ListDevicesByUserRow struct {
	ID             string    `json:"id"`
	UserID         string    `json:"user_id"`
	DeviceName     string    `json:"device_name"`
	PublicKey      string    `json:"public_key"`
	WrappedUserKey string    `json:"wrapped_user_key"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]ListDevicesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesByUserRow
	for rows.Next() {
		var i ListDevicesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.PublicKey,
			&i.WrappedUserKey,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedNoteChanges = `-- name: ListEncryptedNoteChanges :many
SELECT id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM encrypted_notes
WHERE user_id::text = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListEncryptedNoteChangesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type ListEncryptedNoteChangesRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListEncryptedNoteChanges(ctx context.Context, arg ListEncryptedNoteChangesParams) ([]ListEncryptedNoteChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedNoteChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncryptedNoteChangesRow
	for rows.Next() {
		var i ListEncryptedNoteChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.PayloadSize,
			&i.Version,
			&i.RecordingRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedRecordingChanges = `-- name: ListEncryptedRecordingChanges :many
SELECT id::text, user_id::text, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at, deleted_at
FROM encrypted_recordings
WHERE user_id::text = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type ListEncryptedRecordingChangesParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type ListEncryptedRecordingChangesRow struct {
	ID            string       `json:"id"`
	UserID        string       `json:"user_id"`
	ObjectKey     string       `json:"object_key"`
	SizeBytes     int64        `json:"size_bytes"`
	ContentNonce  []byte       `json:"content_nonce"`
	EncryptedMeta []byte       `json:"encrypted_meta"`
	Version       int32        `json:"version"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListEncryptedRecordingChanges(ctx context.Context, arg ListEncryptedRecordingChangesParams) ([]ListEncryptedRecordingChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedRecordingChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncryptedRecordingChangesRow
	for rows.Next() {
		var i ListEncryptedRecordingChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentNonce,
			&i.EncryptedMeta,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingOwnedByUser = `-- name: RecordingOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM encrypted_recordings
  WHERE object_key = $1 AND user_id::text = $2
)
`

type RecordingOwnedByUserParams struct {
	ObjectKey string    `json:"object_key"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordingOwnedByUser(ctx context.Context, arg RecordingOwnedByUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, recordingOwnedByUser, arg.ObjectKey, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const softDeleteEncryptedNote = `-- name: SoftDeleteEncryptedNote :execrows
UPDATE encrypted_notes
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id::text = $1 AND user_id::text = $2 AND deleted_at IS NULL
`

type SoftDeleteEncryptedNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteEncryptedNote(ctx context.Context, arg SoftDeleteEncryptedNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncryptedNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteEncryptedRecording = `-- name: SoftDeleteEncryptedRecording :execrows
UPDATE encrypted_recordings
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id::text = $1 AND user_id::text = $2 AND deleted_at IS NULL
`

type SoftDeleteEncryptedRecordingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteEncryptedRecording(ctx context.Context, arg SoftDeleteEncryptedRecordingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncryptedRecording, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceKey = `-- name: UpdateDeviceKey :execrows
UPDATE devices
SET wrapped_user_key = $1, last_seen_at = CURRENT_TIMESTAMP
WHERE id::text = $2 AND user_id::text = $3
`

type UpdateDeviceKeyParams struct {
	WrappedUserKey string    `json:"wrapped_user_key"`
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateDeviceKey(ctx context.Context, arg UpdateDeviceKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeviceKey, arg.WrappedUserKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEncryptedNote = `-- name: UpdateEncryptedNote :one
UPDATE encrypted_notes
SET object_key = $1, payload_size = $2, recording_ref = $3,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id::text = $4 AND user_id::text = $5 AND version = $6
RETURNING id::text, user_id::text, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type UpdateEncryptedNoteParams struct {
	ObjectKey    string    `json:"object_key"`
	PayloadSize  int64     `json:"payload_size"`
	RecordingRef string    `json:"recording_ref"`
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Version      int32     `json:"version"`
}

type UpdateEncryptedNoteRow struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	ObjectKey    string       `json:"object_key"`
	PayloadSize  int64        `json:"payload_size"`
	Version      int32        `json:"version"`
	RecordingRef string       `json:"recording_ref"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpdateEncryptedNote(ctx context.Context, arg UpdateEncryptedNoteParams) (UpdateEncryptedNoteRow, error) {
	row := q.db.QueryRowContext(ctx, updateEncryptedNote,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i UpdateEncryptedNoteRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (id, user_id, device_id, entity, cursor, updated_at)
VALUES (gen_random_uuid(), $1::uuid, $2::uuid, $3, $4, NOW())
ON CONFLICT (device_id, entity)
DO UPDATE SET cursor = $4, updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Entity  string    `json:"entity"`
	Cursor  time.Time `json:"cursor"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor,
		arg.Column1,
		arg.Column2,
		arg.Entity,
		arg.Cursor,
	)
	return err
}
