// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqliteqlc

import (
	"context"
	"database/sql"
)

const cancelSubscriptionByUser = `-- name: CancelSubscriptionByUser :exec
UPDATE subscriptions SET status = 'canceled', updated_at = CURRENT_TIMESTAMP WHERE user_id = ?
`

func (q *Queries) CancelSubscriptionByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, cancelSubscriptionByUser, userID)
	return err
}

const getSubscriptionByUser = `-- name: GetSubscriptionByUser :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id,
       status, plan_id, current_period_end, created_at, updated_at
FROM subscriptions
WHERE user_id = ?
`

func (q *Queries) GetSubscriptionByUser(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByUser, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
		&i.PlanID,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPremiumFlag = `-- name: GetUserPremiumFlag :one
SELECT is_premium FROM users WHERE id = ?
`

func (q *Queries) GetUserPremiumFlag(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserPremiumFlag, id)
	var is_premium int64
	err := row.Scan(&is_premium)
	return is_premium, err
}

const setUserPremiumFalse = `-- name: SetUserPremiumFalse :exec
UPDATE users SET is_premium = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SetUserPremiumFalse(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setUserPremiumFalse, id)
	return err
}

const setUserPremiumTrue = `-- name: SetUserPremiumTrue :exec
UPDATE users SET is_premium = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SetUserPremiumTrue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setUserPremiumTrue, id)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO subscriptions (id, user_id, stripe_customer_id, stripe_subscription_id, status, plan_id, current_period_end, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE SET
  stripe_customer_id = excluded.stripe_customer_id,
  stripe_subscription_id = excluded.stripe_subscription_id,
  status = excluded.status,
  plan_id = excluded.plan_id,
  current_period_end = excluded.current_period_end,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertSubscriptionParams struct {
	UserID               string         `json:"user_id"`
	StripeCustomerID     string         `json:"stripe_customer_id"`
	StripeSubscriptionID string         `json:"stripe_subscription_id"`
	Status               string         `json:"status"`
	PlanID               string         `json:"plan_id"`
	CurrentPeriodEnd     sql.NullString `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSubscription,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Status,
		arg.PlanID,
		arg.CurrentPeriodEnd,
	)
	return err
}
