// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqliteqlc

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, 'pending', ?, '', '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	UserID   string `json:"user_id"`
	Type     string `json:"type"`
	InputRef string `json:"input_ref"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.UserID, arg.Type, arg.InputRef)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.InputRef,
		&i.OutputRef,
		&i.Error,
		&i.WorkerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobByIDForUser = `-- name: GetJobByIDForUser :one
SELECT id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE id = ? AND user_id = ?
`

type GetJobByIDForUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetJobByIDForUser(ctx context.Context, arg GetJobByIDForUserParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByIDForUser, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.InputRef,
		&i.OutputRef,
		&i.Error,
		&i.WorkerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListJobsByUser(ctx context.Context, userID string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.InputRef,
			&i.OutputRef,
			&i.Error,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUserAndType = `-- name: ListJobsByUserAndType :many
SELECT id, user_id, type, status, input_ref, output_ref, error, worker_id, created_at, updated_at, started_at, finished_at
FROM jobs
WHERE user_id = ? AND type = ?
ORDER BY created_at DESC
LIMIT 50
`

type ListJobsByUserAndTypeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) ListJobsByUserAndType(ctx context.Context, arg ListJobsByUserAndTypeParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUserAndType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.InputRef,
			&i.OutputRef,
			&i.Error,
			&i.WorkerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = ?, output_ref = ?, error = ?,
    started_at = COALESCE(?, started_at),
    finished_at = COALESCE(?, finished_at),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status     string         `json:"status"`
	OutputRef  string         `json:"output_ref"`
	Error      string         `json:"error"`
	StartedAt  sql.NullString `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.OutputRef,
		arg.Error,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}
