// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliteqlc

import (
	"database/sql"
)

type Device struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	DeviceName     string `json:"device_name"`
	PublicKey      string `json:"public_key"`
	WrappedUserKey string `json:"wrapped_user_key"`
	LastSeenAt     string `json:"last_seen_at"`
	CreatedAt      string `json:"created_at"`
}

type Job struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Type       string         `json:"type"`
	Status     string         `json:"status"`
	InputRef   string         `json:"input_ref"`
	OutputRef  string         `json:"output_ref"`
	Error      string         `json:"error"`
	WorkerID   string         `json:"worker_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	StartedAt  sql.NullString `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
}

type Session struct {
	ID            string      `json:"id"`
	UserID        string      `json:"user_id"`
	Token         string      `json:"token"`
	DeviceID      interface{} `json:"device_id"`
	DeviceOs      interface{} `json:"device_os"`
	DeviceVersion interface{} `json:"device_version"`
	DeviceName    interface{} `json:"device_name"`
	ExpiresAt     string      `json:"expires_at"`
	CreatedAt     string      `json:"created_at"`
}

type Subscription struct {
	ID                   string         `json:"id"`
	UserID               string         `json:"user_id"`
	StripeCustomerID     string         `json:"stripe_customer_id"`
	StripeSubscriptionID string         `json:"stripe_subscription_id"`
	Status               string         `json:"status"`
	PlanID               string         `json:"plan_id"`
	CurrentPeriodEnd     sql.NullString `json:"current_period_end"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

type SyncCursor struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	DeviceID  string `json:"device_id"`
	Entity    string `json:"entity"`
	Cursor    string `json:"cursor"`
	UpdatedAt string `json:"updated_at"`
}

type SyncNote struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	ObjectKey    string         `json:"object_key"`
	PayloadSize  int64          `json:"payload_size"`
	Version      int64          `json:"version"`
	RecordingRef string         `json:"recording_ref"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	DeletedAt    sql.NullString `json:"deleted_at"`
}

type SyncRecording struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	ObjectKey    string         `json:"object_key"`
	SizeBytes    int64          `json:"size_bytes"`
	ContentNonce []byte         `json:"content_nonce"`
	Meta         []byte         `json:"meta"`
	Version      int64          `json:"version"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
	DeletedAt    sql.NullString `json:"deleted_at"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	IsPremium    int64  `json:"is_premium"`
	IsAdmin      int64  `json:"is_admin"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}
