// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqliteqlc

import (
	"context"
)

type Querier interface {
	CancelSubscriptionByUser(ctx context.Context, userID string) error
	CountAdmins(ctx context.Context) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateEncryptedNote(ctx context.Context, arg CreateEncryptedNoteParams) (EncryptedNote, error)
	CreateEncryptedRecording(ctx context.Context, arg CreateEncryptedRecordingParams) (EncryptedRecording, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserAdmin(ctx context.Context, arg CreateUserAdminParams) (User, error)
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSessionByID(ctx context.Context, id string) error
	DeleteSessionByToken(ctx context.Context, token string) error
	GetEncryptedNote(ctx context.Context, arg GetEncryptedNoteParams) (EncryptedNote, error)
	GetJobByIDForUser(ctx context.Context, arg GetJobByIDForUserParams) (Job, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSubscriptionByUser(ctx context.Context, userID string) (Subscription, error)
	GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (string, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPremiumFlag(ctx context.Context, id string) (int64, error)
	ListDevicesByUser(ctx context.Context, userID string) ([]Device, error)
	ListEncryptedNoteChanges(ctx context.Context, arg ListEncryptedNoteChangesParams) ([]EncryptedNote, error)
	ListEncryptedRecordingChanges(ctx context.Context, arg ListEncryptedRecordingChangesParams) ([]EncryptedRecording, error)
	ListJobsByUser(ctx context.Context, userID string) ([]Job, error)
	ListJobsByUserAndType(ctx context.Context, arg ListJobsByUserAndTypeParams) ([]Job, error)
	RecordingOwnedByUser(ctx context.Context, arg RecordingOwnedByUserParams) (int64, error)
	SetUserPremium(ctx context.Context, arg SetUserPremiumParams) error
	SetUserPremiumFalse(ctx context.Context, id string) error
	SetUserPremiumTrue(ctx context.Context, id string) error
	SoftDeleteEncryptedNote(ctx context.Context, arg SoftDeleteEncryptedNoteParams) (int64, error)
	SoftDeleteEncryptedRecording(ctx context.Context, arg SoftDeleteEncryptedRecordingParams) (int64, error)
	UpdateDeviceKey(ctx context.Context, arg UpdateDeviceKeyParams) (int64, error)
	UpdateEncryptedNote(ctx context.Context, arg UpdateEncryptedNoteParams) (EncryptedNote, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error
	UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error
}

var _ Querier = (*Queries)(nil)
