// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package sqliteqlc

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at
`

type CreateDeviceParams struct {
	UserID     string `json:"user_id"`
	DeviceName string `json:"device_name"`
	PublicKey  string `json:"public_key"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.UserID, arg.DeviceName, arg.PublicKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.PublicKey,
		&i.WrappedUserKey,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSyncNote = `-- name: CreateSyncNote :one
INSERT INTO sync_notes (id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, 1, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type CreateSyncNoteParams struct {
	UserID       string `json:"user_id"`
	ObjectKey    string `json:"object_key"`
	PayloadSize  int64  `json:"payload_size"`
	RecordingRef string `json:"recording_ref"`
}

func (q *Queries) CreateSyncNote(ctx context.Context, arg CreateSyncNoteParams) (SyncNote, error) {
	row := q.db.QueryRowContext(ctx, createSyncNote,
		arg.UserID,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
	)
	var i SyncNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSyncRecording = `-- name: CreateSyncRecording :one
INSERT INTO sync_recordings (id, user_id, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at, deleted_at
`

type CreateSyncRecordingParams struct {
	UserID       string `json:"user_id"`
	ObjectKey    string `json:"object_key"`
	SizeBytes    int64  `json:"size_bytes"`
	ContentNonce []byte `json:"content_nonce"`
	Meta         []byte `json:"meta"`
}

func (q *Queries) CreateSyncRecording(ctx context.Context, arg CreateSyncRecordingParams) (SyncRecording, error) {
	row := q.db.QueryRowContext(ctx, createSyncRecording,
		arg.UserID,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentNonce,
		arg.Meta,
	)
	var i SyncRecording
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentNonce,
		&i.Meta,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ? AND user_id = ?
`

type DeleteDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor
FROM sync_cursors
WHERE device_id = ? AND entity = ?
`

type GetSyncCursorParams struct {
	DeviceID string `json:"device_id"`
	Entity   string `json:"entity"`
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.DeviceID, arg.Entity)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const getSyncNote = `-- name: GetSyncNote :one
SELECT id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM sync_notes
WHERE id = ? AND user_id = ?
`

type GetSyncNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSyncNote(ctx context.Context, arg GetSyncNoteParams) (SyncNote, error) {
	row := q.db.QueryRowContext(ctx, getSyncNote, arg.ID, arg.UserID)
	var i SyncNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at
FROM devices
WHERE user_id = ?
ORDER BY created_at
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.PublicKey,
			&i.WrappedUserKey,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncNoteChanges = `-- name: ListSyncNoteChanges :many
SELECT id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM sync_notes
WHERE user_id = ? AND updated_at > ?
ORDER BY updated_at ASC
LIMIT ?
`

type ListSyncNoteChangesParams struct {
	UserID    string `json:"user_id"`
	UpdatedAt string `json:"updated_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListSyncNoteChanges(ctx context.Context, arg ListSyncNoteChangesParams) ([]SyncNote, error) {
	rows, err := q.db.QueryContext(ctx, listSyncNoteChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncNote
	for rows.Next() {
		var i SyncNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.PayloadSize,
			&i.Version,
			&i.RecordingRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRecordingChanges = `-- name: ListSyncRecordingChanges :many
SELECT id, user_id, object_key, size_bytes, content_nonce, meta, version, created_at, updated_at, deleted_at
FROM sync_recordings
WHERE user_id = ? AND updated_at > ?
ORDER BY updated_at ASC
LIMIT ?
`

type ListSyncRecordingChangesParams struct {
	UserID    string `json:"user_id"`
	UpdatedAt string `json:"updated_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListSyncRecordingChanges(ctx context.Context, arg ListSyncRecordingChangesParams) ([]SyncRecording, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRecordingChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncRecording
	for rows.Next() {
		var i SyncRecording
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentNonce,
			&i.Meta,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingOwnedByUser = `-- name: RecordingOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM sync_recordings
  WHERE object_key = ? AND user_id = ?
)
`

type RecordingOwnedByUserParams struct {
	ObjectKey string `json:"object_key"`
	UserID    string `json:"user_id"`
}

func (q *Queries) RecordingOwnedByUser(ctx context.Context, arg RecordingOwnedByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordingOwnedByUser, arg.ObjectKey, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteSyncNote = `-- name: SoftDeleteSyncNote :execrows
UPDATE sync_notes
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteSyncNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteSyncNote(ctx context.Context, arg SoftDeleteSyncNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteSyncNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteSyncRecording = `-- name: SoftDeleteSyncRecording :execrows
UPDATE sync_recordings
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteSyncRecordingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteSyncRecording(ctx context.Context, arg SoftDeleteSyncRecordingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteSyncRecording, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceKey = `-- name: UpdateDeviceKey :execrows
UPDATE devices
SET wrapped_user_key = ?, last_seen_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateDeviceKeyParams struct {
	WrappedUserKey string `json:"wrapped_user_key"`
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpdateDeviceKey(ctx context.Context, arg UpdateDeviceKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeviceKey, arg.WrappedUserKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSyncNote = `-- name: UpdateSyncNote :one
UPDATE sync_notes
SET object_key = ?, payload_size = ?, recording_ref = ?,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND version = ?
RETURNING id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type UpdateSyncNoteParams struct {
	ObjectKey    string `json:"object_key"`
	PayloadSize  int64  `json:"payload_size"`
	RecordingRef string `json:"recording_ref"`
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	Version      int64  `json:"version"`
}

func (q *Queries) UpdateSyncNote(ctx context.Context, arg UpdateSyncNoteParams) (SyncNote, error) {
	row := q.db.QueryRowContext(ctx, updateSyncNote,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i SyncNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (id, user_id, device_id, entity, cursor, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (device_id, entity)
DO UPDATE SET cursor = excluded.cursor, updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Entity   string `json:"entity"`
	Cursor   string `json:"cursor"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor,
		arg.UserID,
		arg.DeviceID,
		arg.Entity,
		arg.Cursor,
	)
	return err
}
