// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package sqliteqlc

import (
	"context"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at
`

type CreateDeviceParams struct {
	UserID     string `json:"user_id"`
	DeviceName string `json:"device_name"`
	PublicKey  string `json:"public_key"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.UserID, arg.DeviceName, arg.PublicKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.PublicKey,
		&i.WrappedUserKey,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEncryptedNote = `-- name: CreateEncryptedNote :one
INSERT INTO encrypted_notes (id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, 1, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type CreateEncryptedNoteParams struct {
	UserID       string `json:"user_id"`
	ObjectKey    string `json:"object_key"`
	PayloadSize  int64  `json:"payload_size"`
	RecordingRef string `json:"recording_ref"`
}

func (q *Queries) CreateEncryptedNote(ctx context.Context, arg CreateEncryptedNoteParams) (EncryptedNote, error) {
	row := q.db.QueryRowContext(ctx, createEncryptedNote,
		arg.UserID,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
	)
	var i EncryptedNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEncryptedRecording = `-- name: CreateEncryptedRecording :one
INSERT INTO encrypted_recordings (id, user_id, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, ?, ?, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, user_id, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at, deleted_at
`

type CreateEncryptedRecordingParams struct {
	UserID        string `json:"user_id"`
	ObjectKey     string `json:"object_key"`
	SizeBytes     int64  `json:"size_bytes"`
	ContentNonce  []byte `json:"content_nonce"`
	EncryptedMeta []byte `json:"encrypted_meta"`
}

func (q *Queries) CreateEncryptedRecording(ctx context.Context, arg CreateEncryptedRecordingParams) (EncryptedRecording, error) {
	row := q.db.QueryRowContext(ctx, createEncryptedRecording,
		arg.UserID,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.ContentNonce,
		arg.EncryptedMeta,
	)
	var i EncryptedRecording
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ContentNonce,
		&i.EncryptedMeta,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = ? AND user_id = ?
`

type DeleteDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getEncryptedNote = `-- name: GetEncryptedNote :one
SELECT id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM encrypted_notes
WHERE id = ? AND user_id = ?
`

type GetEncryptedNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetEncryptedNote(ctx context.Context, arg GetEncryptedNoteParams) (EncryptedNote, error) {
	row := q.db.QueryRowContext(ctx, getEncryptedNote, arg.ID, arg.UserID)
	var i EncryptedNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT cursor
FROM sync_cursors
WHERE device_id = ? AND entity = ?
`

type GetSyncCursorParams struct {
	DeviceID string `json:"device_id"`
	Entity   string `json:"entity"`
}

func (q *Queries) GetSyncCursor(ctx context.Context, arg GetSyncCursorParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, arg.DeviceID, arg.Entity)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, device_name, public_key, wrapped_user_key, last_seen_at, created_at
FROM devices
WHERE user_id = ?
ORDER BY created_at
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.PublicKey,
			&i.WrappedUserKey,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedNoteChanges = `-- name: ListEncryptedNoteChanges :many
SELECT id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
FROM encrypted_notes
WHERE user_id = ? AND updated_at > ?
ORDER BY updated_at ASC
LIMIT ?
`

type ListEncryptedNoteChangesParams struct {
	UserID    string `json:"user_id"`
	UpdatedAt string `json:"updated_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListEncryptedNoteChanges(ctx context.Context, arg ListEncryptedNoteChangesParams) ([]EncryptedNote, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedNoteChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedNote
	for rows.Next() {
		var i EncryptedNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.PayloadSize,
			&i.Version,
			&i.RecordingRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncryptedRecordingChanges = `-- name: ListEncryptedRecordingChanges :many
SELECT id, user_id, object_key, size_bytes, content_nonce, encrypted_meta, version, created_at, updated_at, deleted_at
FROM encrypted_recordings
WHERE user_id = ? AND updated_at > ?
ORDER BY updated_at ASC
LIMIT ?
`

type ListEncryptedRecordingChangesParams struct {
	UserID    string `json:"user_id"`
	UpdatedAt string `json:"updated_at"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListEncryptedRecordingChanges(ctx context.Context, arg ListEncryptedRecordingChangesParams) ([]EncryptedRecording, error) {
	rows, err := q.db.QueryContext(ctx, listEncryptedRecordingChanges, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EncryptedRecording
	for rows.Next() {
		var i EncryptedRecording
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ContentNonce,
			&i.EncryptedMeta,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordingOwnedByUser = `-- name: RecordingOwnedByUser :one
SELECT EXISTS(
  SELECT 1 FROM encrypted_recordings
  WHERE object_key = ? AND user_id = ?
)
`

type RecordingOwnedByUserParams struct {
	ObjectKey string `json:"object_key"`
	UserID    string `json:"user_id"`
}

func (q *Queries) RecordingOwnedByUser(ctx context.Context, arg RecordingOwnedByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, recordingOwnedByUser, arg.ObjectKey, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const softDeleteEncryptedNote = `-- name: SoftDeleteEncryptedNote :execrows
UPDATE encrypted_notes
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteEncryptedNoteParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteEncryptedNote(ctx context.Context, arg SoftDeleteEncryptedNoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncryptedNote, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteEncryptedRecording = `-- name: SoftDeleteEncryptedRecording :execrows
UPDATE encrypted_recordings
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, version = version + 1
WHERE id = ? AND user_id = ? AND deleted_at IS NULL
`

type SoftDeleteEncryptedRecordingParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) SoftDeleteEncryptedRecording(ctx context.Context, arg SoftDeleteEncryptedRecordingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteEncryptedRecording, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeviceKey = `-- name: UpdateDeviceKey :execrows
UPDATE devices
SET wrapped_user_key = ?, last_seen_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateDeviceKeyParams struct {
	WrappedUserKey string `json:"wrapped_user_key"`
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpdateDeviceKey(ctx context.Context, arg UpdateDeviceKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeviceKey, arg.WrappedUserKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateEncryptedNote = `-- name: UpdateEncryptedNote :one
UPDATE encrypted_notes
SET object_key = ?, payload_size = ?, recording_ref = ?,
    version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND version = ?
RETURNING id, user_id, object_key, payload_size, version, recording_ref, created_at, updated_at, deleted_at
`

type UpdateEncryptedNoteParams struct {
	ObjectKey    string `json:"object_key"`
	PayloadSize  int64  `json:"payload_size"`
	RecordingRef string `json:"recording_ref"`
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	Version      int64  `json:"version"`
}

func (q *Queries) UpdateEncryptedNote(ctx context.Context, arg UpdateEncryptedNoteParams) (EncryptedNote, error) {
	row := q.db.QueryRowContext(ctx, updateEncryptedNote,
		arg.ObjectKey,
		arg.PayloadSize,
		arg.RecordingRef,
		arg.ID,
		arg.UserID,
		arg.Version,
	)
	var i EncryptedNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.PayloadSize,
		&i.Version,
		&i.RecordingRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursors (id, user_id, device_id, entity, cursor, updated_at)
VALUES (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (device_id, entity)
DO UPDATE SET cursor = excluded.cursor, updated_at = CURRENT_TIMESTAMP
`

type UpsertSyncCursorParams struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Entity   string `json:"entity"`
	Cursor   string `json:"cursor"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor,
		arg.UserID,
		arg.DeviceID,
		arg.Entity,
		arg.Cursor,
	)
	return err
}
